In [8]:
import os
os.getcwd()

'C:\\Users\\yashl\\OneDrive\\Desktop\\Nassau_Route_Analysis\\notebooks'

In [3]:
os.listdir()

['.ipynb_checkpoints',
 '003_features_engineering.ipynb',
 '1_data_loading.ipynb',
 '2_data_cleaning.ipynb',
 '3_EDA_.ipynb',
 '4_route_analsis.ipynb']

In [12]:
print(os.listdir("data"))

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data'

In [13]:
print(os.listdir("../data"))

['.ipynb_checkpoints', 'processed', 'raw']

In [15]:
import pandas as pd 
df = pd.read_csv("data/processed/2_data_cleaning.ipynb")

FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/2_data_cleaning.ipynb'

In [16]:
import os
print(os.getcwd())

C:\Users\yashl\OneDrive\Desktop\Nassau_Route_Analysis\notebooks

In [17]:
df = pd.read_csv("../data/processed/clean_shipping_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/processed/clean_shipping_data.csv'

In [18]:
os.getcwd()

'C:\\Users\\yashl\\OneDrive\\Desktop\\Nassau_Route_Analysis\\notebooks'

In [21]:
import os

print(os.listdir("../data"))

['.ipynb_checkpoints', 'processed', 'raw']

In [20]:
print(os.listdir("../data/processed"))

['.ipynb_checkpoints', '2_data_cleaning.ipynb']

In [22]:
import os
print(os.getcwd())

C:\Users\yashl\OneDrive\Desktop\Nassau_Route_Analysis\notebooks

In [23]:
print(os.listdir(".."))

['.ipynb_checkpoints', '2_data_cleaning.ipynb', 'data', 'notebooks', 'src', 'venv']

In [24]:
print(os.listdir("../data"))

['.ipynb_checkpoints', 'processed', 'raw']

In [25]:
print(os.listdir("../data/processed"))

['.ipynb_checkpoints', '2_data_cleaning.ipynb']

In [26]:
print(os.listdir("../data/processed"))

['.ipynb_checkpoints', 'clean_shipping_data.csv']

In [2]:
import pandas as pd

df = pd.read_csv("../data/processed/clean_shipping_data.csv")

In [3]:
product_factory = {
    "Wonka Bar - Nutty Crunch Surprise": "Lot's O' Nuts",
    "Wonka Bar - Fudge Mallows": "Lot's O' Nuts",
    "Wonka Bar -Scrumdiddlyumptious": "Lot's O' Nuts",
    "Wonka Bar - Milk Chocolate": "Wicked Choccy's",
    "Wonka Bar - Triple Dazzle Caramel": "Wicked Choccy's",
    "Laffy Taffy": "Sugar Shack",
    "SweeTARTS": "Sugar Shack",
    "Nerds": "Sugar Shack",
    "Fun Dip": "Sugar Shack",
    "Fizzy Lifting Drinks": "Sugar Shack",
    "Everlasting Gobstopper": "Secret Factory",
    "Hair Toffee": "The Other Factory",
    "Lickable Wallpaper": "Secret Factory",
    "Wonka Gum": "Secret Factory",
    "Kazookles": "The Other Factory"
}

In [4]:
df["Factory"] = df["Product Name"].map(product_factory)

In [5]:
df[["Product Name", "Factory"]].head(15)

                         Product Name          Factory
0          Wonka Bar - Milk Chocolate  Wicked Choccy's
1   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
2   Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
3      Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
4   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
5      Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
6   Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's
7          Wonka Bar - Milk Chocolate  Wicked Choccy's
8   Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
9          Wonka Bar - Milk Chocolate  Wicked Choccy's
10         Wonka Bar - Milk Chocolate  Wicked Choccy's
11         Wonka Bar - Milk Chocolate  Wicked Choccy's
12     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
13          Wonka Bar - Fudge Mallows    Lot's O' Nuts
14         Wonka Bar - Milk Chocolate  Wicked Choccy's

In [6]:
df["Factory"].isnull().sum()

np.int64(0)

In [7]:
factory_coordinates = {
    "Lot's O' Nuts": (32.881893, -111.768036),
    "Wicked Choccy's": (32.076176, -81.088371),
    "Sugar Shack": (48.119140, -96.181150),
    "Secret Factory": (41.446333, -90.565487),
    "The Other Factory": (35.117500, -89.971107)
}

In [8]:
df["Factory Latitude"] = df["Factory"].map(
    lambda x: factory_coordinates[x][0]
)

In [9]:
df["Factory Longitude"] = df["Factory"].map(
    lambda x: factory_coordinates[x][1]
)

In [10]:
df[[
    "Factory",
    "Factory Latitude",
    "Factory Longitude"
]].head(10)

           Factory  Factory Latitude  Factory Longitude
0  Wicked Choccy's         32.076176         -81.088371
1  Wicked Choccy's         32.076176         -81.088371
2    Lot's O' Nuts         32.881893        -111.768036
3    Lot's O' Nuts         32.881893        -111.768036
4  Wicked Choccy's         32.076176         -81.088371
5    Lot's O' Nuts         32.881893        -111.768036
6  Wicked Choccy's         32.076176         -81.088371
7  Wicked Choccy's         32.076176         -81.088371
8    Lot's O' Nuts         32.881893        -111.768036
9  Wicked Choccy's         32.076176         -81.088371

In [11]:
df["Factory_State_Route"] = (
    df["Factory"] + " → " + df["State/Province"]
)

In [12]:
df[["Factory", "State/Province", "Factory_State_Route"]].head(10)

           Factory State/Province             Factory_State_Route
0  Wicked Choccy's          Texas         Wicked Choccy's → Texas
1  Wicked Choccy's       Illinois      Wicked Choccy's → Illinois
2    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
3    Lot's O' Nuts       Illinois        Lot's O' Nuts → Illinois
4  Wicked Choccy's   Pennsylvania  Wicked Choccy's → Pennsylvania
5    Lot's O' Nuts       Kentucky        Lot's O' Nuts → Kentucky
6  Wicked Choccy's       Kentucky      Wicked Choccy's → Kentucky
7  Wicked Choccy's        Georgia       Wicked Choccy's → Georgia
8    Lot's O' Nuts       Kentucky        Lot's O' Nuts → Kentucky
9  Wicked Choccy's       Kentucky      Wicked Choccy's → Kentucky

In [13]:
df["Factory_Region_Route"] = (
    df["Factory"] + " → " + df["Region"]
)

In [14]:
df[["Factory", "Region", "Factory_Region_Route"]].head(10)

           Factory    Region        Factory_Region_Route
0  Wicked Choccy's  Interior  Wicked Choccy's → Interior
1  Wicked Choccy's  Interior  Wicked Choccy's → Interior
2    Lot's O' Nuts  Interior    Lot's O' Nuts → Interior
3    Lot's O' Nuts  Interior    Lot's O' Nuts → Interior
4  Wicked Choccy's  Atlantic  Wicked Choccy's → Atlantic
5    Lot's O' Nuts      Gulf        Lot's O' Nuts → Gulf
6  Wicked Choccy's      Gulf      Wicked Choccy's → Gulf
7  Wicked Choccy's      Gulf      Wicked Choccy's → Gulf
8    Lot's O' Nuts      Gulf        Lot's O' Nuts → Gulf
9  Wicked Choccy's      Gulf      Wicked Choccy's → Gulf

In [15]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost', 'Shipping Lead Time',
       'Delay Flag', 'Factory', 'Factory Latitude', 'Factory Longitude',
       'Factory_State_Route', 'Factory_Region_Route'],
      dtype='str')

In [16]:
region_summary = (
    df.groupby("Region")
      .agg(
          Total_Shipments=("Order ID", "count"),
          Average_Lead_Time=("Shipping Lead Time", "mean")
      )
      .reset_index()
)

In [17]:
region_summary

     Region  Total_Shipments  Average_Lead_Time
0  Atlantic             2986           8.108841
1      Gulf             1620           8.012346
2  Interior             2335           7.919058
3   Pacific             3253           7.934829

In [18]:
state_summary = (
    df.groupby("State/Province")
      .agg(
          Total_Shipments=("Order ID", "count"),
          Average_Lead_Time=("Shipping Lead Time", "mean")
      )
      .reset_index()
)

In [19]:
state_summary.head()

     State/Province  Total_Shipments  Average_Lead_Time
0           Alabama               61           8.016393
1           Alberta               26           7.730769
2           Arizona              224           7.660714
3          Arkansas               60           8.216667
4  British Columbia               22           7.227273

In [20]:
#top ten bottleneck state
bottleneck_states = state_summary.sort_values(
    by="Average_Lead_Time",
    ascending=False
)

bottleneck_states.head(10)

          State/Province  Total_Shipments  Average_Lead_Time
47          Saskatchewan                2          12.500000
53               Vermont               11           9.545455
29                Nevada               39           9.205128
31         New Hampshire               27           9.111111
26              Missouri               66           8.984848
12                 Idaho               21           8.761905
9   District of Columbia               10           8.500000
22         Massachusetts              135           8.451852
50             Tennessee              183           8.448087
20              Manitoba               12           8.416667

In [21]:
#state with high volum but low lead time
high_volume_poor_performance = state_summary[
    (state_summary["Total_Shipments"] > state_summary["Total_Shipments"].median()) &
    (state_summary["Average_Lead_Time"] > state_summary["Average_Lead_Time"].median())
]

high_volume_poor_performance

    State/Province  Total_Shipments  Average_Lead_Time
0          Alabama               61           8.016393
3         Arkansas               60           8.216667
5       California             2001           7.953523
6         Colorado              182           8.076923
14         Indiana              149           8.208054
22   Massachusetts              135           8.451852
24       Minnesota               89           8.168539
26        Missouri               66           8.984848
32      New Jersey              130           8.200000
34        New York             1128           8.384752
36  North Carolina              249           8.373494
40        Oklahoma               66           8.333333
42          Oregon              124           8.233871
43    Pennsylvania              587           7.952300
50       Tennessee              183           8.448087
54        Virginia              224           8.071429
57       Wisconsin              110           7.972727

In [22]:
region_summary.to_csv(
    "../data/processed/region_summary.csv",
    index=False
)

state_summary.to_csv(
    "../data/processed/state_summary.csv",
    index=False
)

bottleneck_states.to_csv(
    "../data/processed/bottleneck_states.csv",
    index=False
)