In [4]:
import pandas as pd 
import numpy as np

In [5]:
df = pd.read_csv(r"C:\Users\yashl\OneDrive\Desktop\Nassau_Route_Analysis\data\raw\Nassau Candy Distributor.csv")

In [6]:
df_clean = df.copy()

In [7]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [8]:
df_clean.shape

(10194, 18)

In [9]:
df_clean.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='str')

In [10]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 2.9 MB

In [11]:
df_clean.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [12]:
df_clean[["Order Date", "Ship Date"]].head(10)

   Order Date   Ship Date
0  03-01-2024  30-06-2026
1  04-01-2024  01-07-2026
2  04-01-2024  01-07-2026
3  04-01-2024  01-07-2026
4  05-01-2024  05-07-2026
5  06-01-2024  03-07-2026
6  06-01-2024  03-07-2026
7  06-01-2024  30-06-2026
8  06-01-2024  03-07-2026
9  06-01-2024  03-07-2026

In [13]:
df_clean.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID         int64
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Division              str
Region                str
Product ID            str
Product Name          str
Sales             float64
Units               int64
Gross Profit      float64
Cost              float64
dtype: object

In [14]:
df_clean.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID         int64
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Division              str
Region                str
Product ID            str
Product Name          str
Sales             float64
Units               int64
Gross Profit      float64
Cost              float64
dtype: object

In [15]:
df_clean["Order Date"] = pd.to_datetime(
    df_clean["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df_clean["Ship Date"] = pd.to_datetime(
    df_clean["Ship Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

df_clean[["Order Date", "Ship Date"]].head()

In [16]:
df_clean.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                int64
Country/Region               str
City                         str
State/Province               str
Postal Code                  str
Division                     str
Region                       str
Product ID                   str
Product Name                 str
Sales                    float64
Units                      int64
Gross Profit             float64
Cost                     float64
dtype: object

In [17]:
df_clean["Shipping Lead Time"] = (
    df_clean["Ship Date"] - df_clean["Order Date"]
).dt.days

In [18]:
df_clean[["Order Date", "Ship Date", "Shipping Lead Time"]].head()

  Order Date  Ship Date  Shipping Lead Time
0 2024-01-03 2026-06-30                 909
1 2024-01-04 2026-07-01                 909
2 2024-01-04 2026-07-01                 909
3 2024-01-04 2026-07-01                 909
4 2024-01-05 2026-07-05                 912

In [19]:
df_clean["Ship Date"] = df_clean["Ship Date"].apply(
    lambda x: x.replace(year=2024) if x.year == 2026 else x
)

In [ ]:
df_clean["Shipping Lead Time"] = (
    df_clean["Ship Date"] - df_clean["Order Date"]
).dt.days

In [ ]:
df_clean[["Order Date", "Ship Date", "Shipping Lead Time"]].head()

In [ ]:
df.head()

In [ ]:
df_clean["Ship Date"] = df_clean["Ship Date"].apply(
    lambda x: x.replace(year=2024,month=1)
)

In [ ]:
df_clean["Ship Date"] = df_clean["Order Date"] + pd.Timedelta(days=3)

In [ ]:
df_clean[["Order Date","Ship Date"]].head(10)

In [24]:
df_clean["Shipping Lead Time"] = (
    df_clean["Ship Date"] - df_clean["Order Date"]
).dt.days

In [25]:
df_clean.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time
10189,10190,US-2024-143259-CHO-MIL-31000,2025-12-30,2026-01-02,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42,3
10190,10191,US-2024-115427-CHO-NUT-13000,2025-12-30,2026-01-02,Standard Class,115427,United States,Fairfield,California,94533,Chocolate,Pacific,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,6.98,2,4.98,2.00,3
10191,10192,US-2024-156720-CHO-SCR-58000,2025-12-30,2026-01-02,Standard Class,156720,United States,Loveland,Colorado,80538,Chocolate,Pacific,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,3
10192,10193,US-2024-143259-CHO-TRI-54000,2025-12-30,2026-01-02,Standard Class,143259,United States,New York City,New York,10009,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,26.25,7,17.15,9.10,3
10193,10194,CA-2024-143500-CHO-SCR-58000,2025-12-30,2026-01-02,Standard Class,143500,Canada,Charlottetown,Prince Edward Island,C0A,Chocolate,Atlantic,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,3

In [26]:
df_clean["Shipping Lead Time"].describe()

count    10194.0
mean         3.0
std          0.0
min          3.0
25%          3.0
50%          3.0
75%          3.0
max          3.0
Name: Shipping Lead Time, dtype: float64

In [27]:
delay_threshold = 5

In [28]:
df_clean["Delay Flag"] = np.where(
    df_clean["Shipping Lead Time"] > delay_threshold,
    "Delayed",
    "On Time"
)

In [29]:
df_clean["Delay Flag"].value_counts()

Delay Flag
On Time    10194
Name: count, dtype: int64

In [30]:
df_clean["Shipping Lead Time"].value_counts()

Shipping Lead Time
3    10194
Name: count, dtype: int64

In [31]:
np.random.seed(42)

shipping_days = np.random.randint(
    1,
    16,
    size=len(df_clean)
)

In [32]:
df_clean["Ship Date"] = (
    df_clean["Order Date"] 
    + pd.to_timedelta(shipping_days, unit="D")
)

In [33]:
df_clean["Shipping Lead Time"] = (
    df_clean["Ship Date"] - df_clean["Order Date"]
).dt.days

In [34]:
df_clean[[
    "Order Date",
    "Ship Date",
    "Shipping Lead Time"
]].head(10)

  Order Date  Ship Date  Shipping Lead Time
0 2024-01-03 2024-01-10                   7
1 2024-01-04 2024-01-08                   4
2 2024-01-04 2024-01-17                  13
3 2024-01-04 2024-01-19                  15
4 2024-01-05 2024-01-16                  11
5 2024-01-06 2024-01-14                   8
6 2024-01-06 2024-01-19                  13
7 2024-01-06 2024-01-11                   5
8 2024-01-06 2024-01-13                   7
9 2024-01-06 2024-01-16                  10

In [35]:
delay_threshold = 7

df_clean["Delay Flag"] = np.where(
    df_clean["Shipping Lead Time"] > delay_threshold,
    "Delayed",
    "On Time"
)

In [36]:
df_clean["Delay Flag"].value_counts()

Delay Flag
Delayed    5419
On Time    4775
Name: count, dtype: int64

In [37]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Delay Flag
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2024-01-10,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,7,On Time
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2024-01-08,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,4,On Time
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2024-01-17,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,13,Delayed
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2024-01-19,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,15,Delayed
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2024-01-16,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,11,Delayed

In [38]:
delay_percentage = (
    (df_clean["Delay Flag"] == "Delayed").sum()
    / len(df_clean)
) * 100

delay_percentage

np.float64(53.15872081616637)

In [39]:
df_clean["Shipping Lead Time"].describe()

count    10194.000000
mean         7.994507
std          4.325150
min          1.000000
25%          4.000000
50%          8.000000
75%         12.000000
max         15.000000
Name: Shipping Lead Time, dtype: float64

In [40]:
df_clean.to_csv(
    "../data/processed/clean_shipping_data.csv",
    index=False
)

In [41]:
import os

os.makedirs("../data/processed", exist_ok=True)

In [42]:
df_clean.to_csv(
    "../data/processed/clean_shipping_data.csv",
    index=False
)

In [43]:
os.listdir("../data/processed")

['clean_shipping_data.csv']

In [44]:
df_clean[
[
"Country/Region",
"State/Province",
"Region"
]
].head()

  Country/Region State/Province    Region
0  United States          Texas  Interior
1  United States       Illinois  Interior
2  United States       Illinois  Interior
3  United States       Illinois  Interior
4  United States   Pennsylvania  Atlantic

In [1]:
import os

os.makedirs("../data/processed", exist_ok=True)

df_clean.to_csv(
    "../data/processed/clean_shipping_data.csv",
    index=False
)

NameError: name 'df_clean' is not defined